#!/usr/bin/env bash
#
# get-env.sh
#
# usage: bash get-env.sh
#
# Generate .env.values configuration file with value of each environment variable,
# from .env file.

cd "$(dirname $0)"
cd ..

echo "=== get environment variables ==="
echo -e "# Generated from .env file\n"\
"# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN\n" > .env.values
envsubst < .env >> .env.values
exit_status=$?
if [[ ${exit_status} -eq 0 ]]; then
  echo "...OK"
else
  >&2 echo "...KO"
  exit ${exit_status}
fi
