name: Continuous Integration

on:
  push:
    branches:
      - "main"
        
jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        os: [ubuntu] # centos
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION="2.11.2"
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      # Local image not recognized in GitHub Actions Workflow else
      - name: Build minimal Ubuntu base docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build-template/krb5-ubuntu/Dockerfile.template
          tags: 
            minimal-ubuntu:latest
          outputs: type=docker,dest=/tmp/minimal-ubuntu.tar
          load: true

      - name: Load minimal Ubuntu docker image
        run: |
          docker load --input /tmp/minimal-ubuntu.tar
          docker image ls -a

      - name: Prepare host machine
        run: |
          ./.ci/install.sh && \
          make gen-conf OS_CONTAINER=${{ matrix.os }}
          
      - name: Install project
        run: |
          docker load --input /tmp/minimal-ubuntu.tar
          make install OS_CONTAINER=${{ matrix.os }} DEBUG=true

      - name: Check version
        run: .ci/check-version.sh
        
      - name: Test
        run: make test
        
      - name: Finish
        run: |
          cat /tmp/krb5-test-${{ matrix.os }}.log && \
          ls -lR && \
          ./script/inspect.sh && \
          ./.ci/check-version.sh
              ./.ci/check-version.sh
