name: Continuous Integration

on:
  push:
    branches:
      - "main"
        
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu] # centos
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION="2.11.2"
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Install project
        run: |
          ./.ci/install.sh && \
          make gen-conf OS_CONTAINER=${{ matrix.os }} && \
          make install OS_CONTAINER=${{ matrix.os }} DEBUG=true

      - name: Check version
        run: .ci/check-version.sh
        
      - name: Test
        run: make test
        
      - name: Finish
        run: |
          cat /tmp/krb5-test-${{ matrix.os }}.log && \
          ls -lR && \
          ./script/inspect.sh && \
          ./.ci/check-version.sh
              ./.ci/check-version.sh
